###############################################################################
# Book settings
title       : Vorlesung Datenanalyse mit Python
author      : EUPhysik
logo        : 'FHDO-Logo-large.svg'
description : Dieses Buch ist das Skript zur Vorlesung 'Datenanalyse mit Python' an der Fachhochschule Dortmund.

###############################################################################
# Exclude settings
exclude_patterns : [.venv/*]

###############################################################################
# Execution settings
execute:
  execute_notebooks : cache
  timeout           : 120

###############################################################################
# TOC settings
only_build_toc_files : true
number_toc_chapters: true

###############################################################################
# HTML-specific settings
html:
  favicon               : 'python_icon.png'
  home_page_in_navbar   : False
  baseurl               : 'https://EUPhysics.github.io/LectureDataAnalysis/'
  use_edit_page_button  : true
  use_issues_button     : true
  use_repository_button : true

###############################################################################
# Interact link settings
# notebook_interface : "notebook"

###############################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright : false
    
###############################################################################
# MyST extensions
parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - html_image
    - amsmath

###############################################################################
# Launch button settings
repository:
  url            : "https://EUPhysics.github.io/LectureDataAnalysis/"
  branch         : main
  path_to_book   : "book"


launch_buttons:
  binderhub_url  : ''
  jupyterhub_url : ''


#latex:
#  latex_engine                : "xelatex"
#  latex_documents:
#    targetname: book.tex
